  - name: Install MySQL Service
    become: yes
    apt: name={{ item }} state=present
    with_items:
      - mysql-server
      - mysql-client


  - name: Replace bind-address in MySQL config with the Internal IP of DB Instance
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^bind-address\s*=\s*.*$'
      line: 'bind-address = 0.0.0.0'    

  - name: Start MySQL Service
    become: yes
    service:
        name: mysql
        state: restarted
        enabled: yes

  - name: Create Application DB
    become: yes
    mysql_db: 
      login_unix_socket: /var/run/mysqld/mysqld.sock
      name: "{{ db_name }}"
      state: present

  - name: Create DB user
    become: yes
    mysql_user:
      name: "{{ db_user }}"
      password: "{{ db_password }}"
      priv: '*.*:ALL'
      state: present   
      host: '%'

  - name: Run SQL file
    mysql_query:
      login_user: "{{ db_user }}"
      login_password: "{{ db_password }}" 
      login_db: "{{ db_name }}"
      query:
        - CREATE TABLE IF NOT EXISTS employees (name VARCHAR(20));
        - INSERT INTO employees VALUES ('JOHN');
